### PR TITLE
Chargediv calib

### PR DESCRIPTION
**Pull request by mortenjc**
### Issue reference / description

The branch you merge from should already reference an event-formation-unit github ticket number. You can add a descriptive title, but if an issue is referenced, you don't have to.

## Checklist for submitter

- [ ] Check for conflict with integration test
- [ ] Unit tests pass

---

### Nominate for Group Code Review

- [ ] Nominate for code review

### CODE REVIEW

**Comment by mortenjc** [comment]
Standalone class and tests to load and apply calibration for the unit interval [0.0 ; 1.0]
Had to invent Unit as substitute for Straw/Tube. Could also be renamed to CDUnit for 
Charge Division thingy. Naming is hard. Not integrated in the data path.

**Review by JennyLouise — CHANGES_REQUESTED** [review]
The content all looks great, but the name CDCalibration doesn't follow good clean code practices, can you give it a more descriptive name? If that would be too long for your liking, can you add a detailed description of what it means to the top of the CDCalibration.h file?

**Comment by mortenjc** [comment]
Good point. This is always a trade off. In any case it should always be clear from the .h file what this does even if the name is not to someones liking and I will update the header file.I might try the long ChargeDivisionCalibration out and see if I can live with it.

**Comment by mortenjc** [comment]
Ok, renaming seemed to be the least of the effort. We can discuss this later. Integration of the code was a lot more work than I thought. But in the process I found a way to transform the loki calibration parameters to the new schemem. Will merge this now to get this initial effort into master.

**Pull request merged**
