### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by mattclarke**
I think it makes sense to start with the "standard" template. It can be made more specific later if required

### CODE REVIEW

**Comment by martukas** [comment]
I don't like this at all.
This is all boring, obvious generic stuff and already feels like busy work.
For example: if branch naming refences either github or JIRA issues, and in particular if separate commits reference issues, the part explaining tickets is superfluous.
Explain test changes? In my latest thing that I did I added a TON of unit tests. There is no way of explaining them other than by going into the code itself. Or maybe nothing was changed in the tests?
"Is the code of an acceptable quality?" Does it make you feel good? etc.. and "To be filled in by the reviewer only" reads like from a form at the tax office.
Reading this has already killed of a piece of my soul.

I thought this was going to have useful reminders like "has anything changed that may require an update of the readme?" or "make sure you have bumped to the latest conan packages while you are at it".

**Comment by zjttoefs** [comment]
@martukas just edit the thing fit your needs. I would agree that the proposal makes the PR rather long. But definitely add the stuff you would like to see. We can later extract these comments and make the templates aligned and better everywhere.

**Comment by mortenjc** [comment]
My main 'objection' to this is that for some reason this has now been 'decided' or declared a good thing which is being rolled out to all repos without prior discussion. Who made the decision is unclear but this happens all the time in Data Management Group. I get a little annoyed as I often feel that the ideas or concerns that I have voiced are not being listened to, whereas other ideas are silently adopted. This lowers my eagerness to suddenly adhere to new 'requirements'.  

Having checklists might or might not be a good thing, but what are we trying to achieve? I am generally in favour of establishing objective criteria to our development process, and generally against subjective ones.

**Comment by zjttoefs** [comment]
@mortenjc GitHub issues may not be the best place to have a discussion on decision processes in general. @mattclarke put you down as reviewer of this pull request to explicitly seek your input.

**Comment by mortenjc** [comment]
implemented directly on master

**Pull request closed without merging**
